name: blocnod_smart_contracts_ui
description: Smart Contract management application.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  injectable: ^2.3.0
  get_it: ^7.6.0
  injectable_generator: ^2.4.0
  flutter_svg: ^2.0.7
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  go_router: ^10.1.0
  equatable: ^2.0.5
  uuid: ^3.0.7
  dio: ^5.3.2


dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3 
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  

flutter:
  uses-material-design: true

  assets:
    - assets/home/
    - assets/money/
    - assets/bottom_bar/
    - assets/contract_state/

  fonts:
    - family: PTSans
      fonts:
        - asset: fonts/PTSans-Regular.ttf
          weight: 400
        - asset: fonts/PTSans-Bold.ttf
          weight: 700
flutter_intl:
  enabled: true
